export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_ERROR = 'SET_ERROR';
export const SET_FETCHING = 'SET_FETCHING';
export const SET_FILTER_SEARCH = 'SET_FILTER_SEARCH';
