export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_SYNCED = 'SET_SYNCED';
export const SET_SYNCING = 'SET_SYNCING';
export const SET_SYNCED_DATE = 'SET_SYNCED_DATE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_SCREEN_HEIGHT = 'SET_SCREEN_HEIGHT';
export const SET_SCREEN_WIDTH = 'SET_SCREEN_WIDTH';
export const SET_URL_QUERY_PARAM = 'SET_URL_QUERY_PARAM';
